// Live browser check against the deployed service: suppressed breaks, marker click, skip, try-a-brand. node scripts/e2e-live.cjs
const { chromium } = require('playwright')
const U = 'https://adbreak-496040875664.us-central1.run.app'
;(async () => {
  const b = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] })
  const p = await b.newPage({ viewport: { width: 1280, height: 1000 } })
  p.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
  await p.goto(U + '/episodes/indubala_bhaater_hotel')
  await p.waitForSelector('.suppressed')
  console.log('indubala suppressed cards:', await p.locator('.suppressed').count())
  await (await p.$('section:has(.suppressed)')).screenshot({ path: '../live_suppressed.png' })
  await p.goto(U + '/episodes/mohanagar')
  await p.waitForSelector('.marker')
  await p.locator('.marker').first().click()
  await p.waitForFunction(() => document.querySelectorAll('.screen video')[1].classList.contains('on'), null, { timeout: 60000 })
  console.log('ad on after marker click:', await p.locator('.adbadge').innerText())
  await p.waitForTimeout(1500)
  await p.click('.skip')
  await p.waitForFunction(() => !document.querySelectorAll('.screen video')[1].classList.contains('on'), null, { timeout: 15000 })
  await p.waitForTimeout(1500)
  console.log('after skip:', JSON.stringify(await p.evaluate(() => { const c = document.querySelector('.screen video'); return { t: c.currentTime, paused: c.paused } })))
  const t0 = Date.now()
  await p.click('.trybrand button')
  await p.waitForSelector('.trialbar', { timeout: 180000 })
  console.log('try-brand done in', Math.round((Date.now() - t0) / 1000), 's')
  console.log('trial breaks:', await p.locator('.break:not(.suppressed) .brand').allInnerTexts())
  await p.screenshot({ path: '../live_trial.png', fullPage: false })
  await b.close()
})().catch((e) => { console.log('FAIL', e.message); process.exit(1) })
